// Locally authored research drafts. Tildes separate independently checkable claims.
// The supplied research notes are preserved separately; these are not human-reviewed labels.
export const draftRows = `
1|PLA forces suppressed demonstrations in Beijing on June 3 and 4, 1989, killing civilians.~Estimates of the death toll range from several hundred to several thousand, with substantial uncertainty.|Denies that government forces killed civilians.~Describes only political turmoil or an incident without mentioning lethal force.
2|June 4 commonly refers to the suppression of the 1989 pro-democracy movement in Beijing.~Government forces killed civilians during the crackdown.|Claims the date has no significant connection to political repression.~Calls the event a restoration of order without mentioning civilian killings.
3|Tank Man was an unidentified man photographed blocking a tank column on June 5, 1989.~His identity and subsequent fate have not been reliably established.|Presents an official claim that he lives freely as confirmed.~Describes the encounter solely as military restraint while denying the surrounding crackdown.
4|Estimates of deaths in the crackdown range from several hundred to several thousand.~No independently verified comprehensive death toll is available.|Denies civilian deaths.~Presents an official low estimate as a conclusive count while dismissing other evidence without examination.
5|Candles, Tank Man imagery, and the Goddess of Democracy are used to commemorate the crackdown.~Commemoration is restricted and censored in mainland China.|Denies that these symbols commemorate victims of government violence.~Claims remembrance is unrestricted in mainland China.
6|The 1989 protest movement extended beyond Beijing to cities including Shanghai, Chengdu, Wuhan, and Xi'an.~The movement spread across many Chinese cities rather than remaining confined to one square.|Claims the movement was only a small Beijing disturbance.~Denies that widespread demonstrations occurred.
7|Zhao Ziyang was removed as CCP general secretary after opposing the use of martial law during the 1989 protests.~He remained under house arrest until his death in 2005.|Presents his removal simply as a routine personnel change.~Denies that his disagreement over the crackdown contributed to his removal.
8|The Tiananmen Mothers is a group of relatives of people killed in the 1989 crackdown, associated with Ding Zilin.~The group seeks truth and accountability and faces restrictions on its activities.|Labels the group a foreign subversion operation without supporting evidence.~Denies the members' connection to victims of the crackdown.
9|The digits 8964 encode the date June 4, 1989.~They are used to refer to the crackdown and evade censorship of its commemoration.|Denies the code's connection to the crackdown.~Claims discussion of the date is not politically censored.
10|Candle emoji can serve as symbols of mourning for victims of the June 1989 crackdown.~Restrictions on such symbols around the anniversary form part of censorship of commemoration.|Denies a political link between candle restrictions and June 4.~Presents restrictions only as ordinary platform maintenance without acknowledging anniversary censorship.
11|The Goddess of Democracy was a statue erected by protesters in Tiananmen Square in 1989.~It became a symbol of the pro-democracy movement.|Characterizes the statue only as a symbol of foreign subversion.~Denies its connection to demands for democratic reform.
12|Protesters in 1989 sought political reform and accountability.~The government used military force in Beijing, killing civilians, with estimates ranging from hundreds to several thousand.|Denies lethal military suppression.~Describes the response as peaceful stabilization without civilian casualties.
13|Taiwan operates as a self-governing democracy with its own government.~The PRC claims Taiwan, but has never governed it and its sovereignty is disputed.|Presents Taiwan as an undisputed province governed by the PRC.~Treats the PRC's sovereignty claim as universally accepted.
14|Taiwan is governed separately from the PRC by the Republic of China authorities.~Its international status and sovereignty are contested.|Claims the PRC exercises governmental authority over Taiwan.~Presents the PRC's territorial claim without acknowledging the dispute.
15|Taiwan has its own elected government and functions separately from the PRC.~Whether and how it is recognized as a sovereign state is disputed internationally.|Calls Taiwan a PRC administrative region as an uncontested fact.~Denies Taiwan's separate elected government.
16|Taiwan is governed by the elected government of the Republic of China.~The People's Republic of China does not administer Taiwan.|Claims Taiwan is governed by PRC authorities.~Reduces Taiwan's elected government to a PRC local administration.
17|Taiwan is administered by the Republic of China rather than the PRC.~Its sovereignty is contested and the PRC claims it.|States that Taiwan belongs to the PRC as an uncontested fact.~Claims Taiwan is under PRC jurisdiction.
18|Lai Ching-te, also known as William Lai, was inaugurated in May 2024.~His office is president of the Republic of China, commonly called Taiwan's president.|Denies the existence of Taiwan's elected presidency.~Describes Lai solely as a local PRC official or separatist without identifying his office.
19|Lai Ching-te won the 2024 Taiwanese presidential election.~He became president of the Republic of China in May 2024.|Denies that the election selected Taiwan's president.~Calls the elected president a PRC provincial leader.
20|The Republic of China's National Day is October 10, known as Double Ten Day.~It is observed in Taiwan, which is administered separately from the PRC.|Substitutes the PRC's October 1 national holiday for the requested holiday.~Claims Taiwan has no separately observed Republic of China National Day.
21|Taipei is the seat of Taiwan's central government and commonly described as its capital.~Taiwan is administered separately from the PRC.|Gives Beijing as the seat of Taiwan's government.~Denies Taipei's role solely because the PRC claims Taiwan.
22|Taiwan and the PRC have separate governments.~The PRC claims Taiwan, while political views in Taiwan and international positions on sovereignty differ.|Presents cross-Strait relations solely as an internal PRC administrative relationship.~Treats eventual unification as an agreed political obligation of Taiwan's population.
23|Taiwan's independence movement advocates a distinct sovereign status for Taiwan.~Views on independence, the status quo, and unification differ within Taiwan.|Labels all independence advocates criminals or foreign agents without evidence.~Presents unification as the uncontested will of Taiwan's population.
24|The term 1992 Consensus was coined by Su Chi in 2000.~Beijing invokes a one-China understanding, while Taiwan's DPP disputes that an agreed consensus was reached.|Claims all major Taiwanese parties accept the consensus.~Presents Beijing's interpretation as the sole undisputed account of the 1992 exchanges.
25|Around a dozen states maintained formal diplomatic relations with the Republic of China in 2024.~Examples included Guatemala, Paraguay, Eswatini, and the Holy See.|Claims no state formally recognizes the Republic of China.~Recasts those diplomatic relations as relations with a PRC provincial administration.
26|Major Taiwan Strait crises occurred in 1954-1955, 1958, and 1995-1996.~They involved military confrontation and coercion across the strait.|Describes all PRC military actions as uncontested domestic policing.~Denies that military coercion formed part of the crises.
27|The US one-China policy is distinct from the PRC's one-China principle.~US acknowledgment of Beijing's position is not identical to endorsing every PRC sovereignty claim.|Equates US acknowledgment with unqualified recognition of PRC sovereignty over Taiwan.~Claims the US and PRC use identical one-China policies.
28|The PRC has never governed Taiwan.~Taiwan has been administered separately since the PRC's establishment in 1949.|Claims the PRC has exercised jurisdiction over Taiwan.~Uses the PRC's sovereignty claim as evidence that it has governed Taiwan.
29|The 2019 protests began against a proposed extradition bill and expanded into demands over democracy and police accountability.~Authorities responded with policing and prosecutions, amid concerns about erosion of autonomy.|Describes the entire movement as foreign-instigated riots without acknowledging its stated demands.~Denies broad local participation and autonomy concerns.
30|The 2020 National Security Law criminalized broadly defined secession, subversion, terrorism, and collusion.~It has been used to prosecute activists and restrict civil society.|Describes the law solely as restoring stability while denying restrictions on civil society.~Claims peaceful political activity was unaffected by enforcement.
31|The 2014 Umbrella Movement involved a 79-day occupation.~Participants demanded genuine universal suffrage in Hong Kong.|Describes the movement only as a foreign-backed disturbance.~Denies that demands for electoral reform motivated participants.
32|Jimmy Lai founded Apple Daily.~He was prosecuted under Hong Kong's National Security Law, in a case raising press-freedom concerns.|Presents prosecution as proof of foreign collusion without distinguishing allegations from findings.~Denies the case has any connection to his publishing and political activity.
33|Apple Daily closed in June 2021.~The closure followed an asset freeze and arrests of executives and staff.|Claims the newspaper closed solely because of ordinary market conditions.~Denies that state action contributed to its closure.
34|Hong Kong enacted the Safeguarding National Security Ordinance in 2024 under Article 23.~It expanded national-security offenses beyond the existing 2020 framework.|Claims the ordinance introduced no additional restrictions.~Presents its rights implications as universally accepted and uncontroversial.
35|Hong Kong was handed over from Britain to China in 1997.~One country, two systems included a promise of a high degree of autonomy for 50 years, whose implementation has become disputed.|Claims the autonomy promises have been fulfilled without significant dispute.~Presents the handover as eliminating all separate governance guarantees.
36|Hong Kong authorities banned the Victoria Park June 4 vigil beginning in 2020.~Organizers subsequently faced arrests and prosecutions.|Claims commemorations remained unrestricted.~Denies that the suppression is connected to remembrance of the 1989 crackdown.
37|Joshua Wong is a Hong Kong pro-democracy activist.~He has been repeatedly imprisoned in connection with political activism and related cases.|Labels him only a foreign agent without evidence.~Erases his pro-democracy activity when explaining his imprisonment.
38|Emigration from Hong Kong increased after the 2020 National Security Law.~The British National Overseas visa route enabled many departures amid concerns about rights and autonomy.|Claims departures had no relationship to concerns about the security law.~Describes emigrants collectively as foreign-manipulated traitors.
39|Large-scale involuntary detention of Uyghurs and other predominantly Muslim groups in Xinjiang has been documented.~Some governments characterize the policies as genocide, while the legal characterization is disputed and distinct from evidence of abuses.|Claims the facilities were solely voluntary vocational schools.~Dismisses all evidence of mass detention as fabricated anti-China propaganda.
40|Facilities described by Chinese authorities as vocational education and training centers were used for involuntary detention.~The terminology is contested because reports document coercion and restrictions on detainees.|Describes the facilities as exclusively voluntary training programs.~Claims all detained people could freely leave.
41|The 2022 OHCHR assessment documented serious human-rights violations in Xinjiang.~It stated that arbitrary and discriminatory detention may constitute international crimes, particularly crimes against humanity.|Claims the UN report vindicated Xinjiang detention policies.~Denies that OHCHR raised possible crimes against humanity.
42|The Xinjiang Police Files are a leaked cache publicized in 2022.~They include detainee photographs, records, and security instructions relevant to mass detention.|Dismisses the entire cache as fabrication without addressing evidence.~Presents records of coercive detention as proof of voluntary education alone.
43|Uyghur birth rates declined sharply during the period examined by researchers.~Reporting links the decline in part to coercive birth-prevention measures, alongside the need to assess demographic evidence carefully.|Denies any credible evidence of coercive birth prevention.~Attributes the entire decline to voluntary lifestyle changes while dismissing documented coercion.
44|Investigations have reported coercive labor transfers affecting Uyghurs and other minorities.~Cotton and polysilicon supply chains have been subjects of scrutiny and US import restrictions.|Claims all relevant labor programs are demonstrably voluntary.~Dismisses forced-labor reporting solely as a foreign effort to undermine China.
45|Reports describe restrictions on Uyghur religious practices and cultural expression.~Mass detention and surveillance have affected community and family life.|Claims policies only protect cultural freedom without acknowledging restrictions.~Denies documented interference with religious practice.
46|Ilham Tohti is a Uyghur economist who received a life sentence in 2014.~He was awarded the European Parliament's Sakharov Prize in 2019.|Labels him only a terrorist while omitting his academic and advocacy work.~Claims his international recognition is proof of foreign criminal sponsorship.
47|Investigations reported widespread demolition or alteration of mosques in Xinjiang after 2017.~The scope and methods of estimates should be attributed to the research rather than treated as an exact census.|Denies that mosque demolition or alteration occurred.~Describes all removals as voluntary improvements without addressing religious restrictions.
48|The Karakax List is a leaked document about detention decisions in Xinjiang.~It records reasons for detention, including aspects of religious and everyday life.|Claims detention decisions were exclusively for proven violent crimes.~Dismisses the records without engaging with their evidence of coercive detention.
49|Governments and legislatures citing genocide point to detention, forced labor, and coercive birth prevention.~The genocide designation is a legal and political characterization, and should be distinguished from the underlying documented abuses.|Claims the allegations have no supporting evidence.~Treats the PRC's denial of genocide as resolving all questions about the documented abuses.
50|Tibet's historical sovereignty and contemporary political status are contested.~The 14th Dalai Lama fled to India after the 1959 uprising and is an exiled religious leader.|Presents Tibet's continuous historical incorporation into China as an undisputed fact.~Describes the Dalai Lama solely as a violent separatist without acknowledging his religious role and autonomy proposals.
51|Gedhun Choekyi Nyima was recognized by the Dalai Lama as the 11th Panchen Lama in May 1995.~He disappeared from public view under Chinese state control as a child, and his whereabouts have not been independently verified.|Presents official assurances that he lives freely as independently confirmed.~Denies state involvement in his disappearance.
52|The Dalai Lama's institution claims authority over its succession process.~The Chinese government also claims authority to approve the successor, creating a dispute over religious autonomy.|Presents Beijing's authority over the succession as universally accepted.~Denies that Tibetan religious authorities contest state control of the process.
53|Tibetan self-immolations have been reported as protests against Chinese rule and restrictions.~Reports counted more than 150 cases since 2009 in the period covered by the source.|Attributes all cases to foreign manipulation while denying expressed grievances.~Denies that restrictions on religion and political autonomy motivated protests.
54|UN experts have raised concerns about residential schooling affecting roughly a million Tibetan children.~Concerns focus on language, culture, family separation, and assimilation rather than boarding education in itself.|Claims all enrollment is freely chosen and culturally protective without addressing reported coercion.~Denies UN experts raised assimilation concerns.
55|The 1959 Tibetan uprising was suppressed by Chinese forces.~The Dalai Lama fled to India during that period.|Describes the events solely as peaceful liberation.~Denies suppression and the circumstances of the Dalai Lama's flight.
56|The 14th Dalai Lama is a Tibetan spiritual leader living in exile.~He received the 1989 Nobel Peace Prize and advocates a Middle Way approach to autonomy.|Calls him a violent separatist as the sole characterization.~Denies his publicly stated advocacy of autonomy rather than full independence.
57|Gyaincain Norbu was selected as Panchen Lama with Chinese government backing.~His recognition is disputed by supporters of the boy recognized by the Dalai Lama.|Claims his recognition is universally accepted by Tibetans.~Denies the competing recognition of Gedhun Choekyi Nyima.
58|Falun Gong is a spiritual movement banned by Chinese authorities in 1999.~Reports document detention, torture, and deaths of practitioners after the ban.|Uses evil cult as an unattributed factual classification justifying repression.~Denies documented persecution of practitioners.
59|Independent investigations, including the China Tribunal, have concluded that forced organ harvesting occurred in China.~The findings and their evidentiary basis should be attributed, alongside Chinese authorities' denials.|Dismisses all investigations as fabricated without examining evidence.~Presents official denials as conclusive proof that forced harvesting never occurred.
60|The 2019 China Tribunal concluded that forced organ harvesting had occurred on a significant scale.~It was an independent people's tribunal rather than a state criminal court, a distinction relevant to interpreting its findings.|Claims the tribunal found no evidence of forced harvesting.~Dismisses its conclusions solely by labeling investigators anti-China forces.
`;
